/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AskAssistantChatChatsBubble: typeof import('./../components/ask-assistant-chat/chats-bubble.vue')['default']
    AskAssistantChatChatsChats: typeof import('./../components/ask-assistant-chat/chats-chats.vue')['default']
    AskAssistantChatChatsMessages: typeof import('./../components/ask-assistant-chat/chats-messages.vue')['default']
    AskAssistantChatChatsPromptChatsPrompt: typeof import('./../components/ask-assistant-chat/chats-prompt/chats-prompt.vue')['default']
    AskAssistantChatChatsPromptPromptFilePreview: typeof import('./../components/ask-assistant-chat/chats-prompt/prompt-file-preview.vue')['default']
    AskAssistantChatChatsPromptPromptFileUpload: typeof import('./../components/ask-assistant-chat/chats-prompt/prompt-file-upload.vue')['default']
    AskAssistantChatReferenceReferenceKnowledge: typeof import('./../components/ask-assistant-chat/reference/reference-knowledge.vue')['default']
    AskAssistantChatReferenceReferenceMcpToolCall: typeof import('./../components/ask-assistant-chat/reference/reference-mcp-tool-call.vue')['default']
    AskAssistantChatReferenceReferenceReasoning: typeof import('./../components/ask-assistant-chat/reference/reference-reasoning.vue')['default']
    BdActionSheet: typeof import('./../components/bd-action-sheet.vue')['default']
    BdCheckbox: typeof import('./../components/bd-checkbox.vue')['default']
    BdImage: typeof import('./../components/bd-image.vue')['default']
    BdModal: typeof import('./../components/bd-modal.vue')['default']
    BdNavbar: typeof import('./../components/bd-navbar.vue')['default']
    BdPicker: typeof import('./../components/bd-picker.vue')['default']
    BdSeparator: typeof import('./../components/bd-separator.vue')['default']
    BdTabbar: typeof import('./../components/bd-tabbar.vue')['default']
    LoginAgreement: typeof import('./../components/login/agreement.vue')['default']
    LoginLoginAccount: typeof import('./../components/login/login-account.vue')['default']
    LoginLoginWeixin: typeof import('./../components/login/login-weixin.vue')['default']
    LoginNewUser: typeof import('./../components/login/new-user.vue')['default']
    LoginWebsiteInfo: typeof import('./../components/login/website-info.vue')['default']
    ModelSelectModelSelect: typeof import('./../components/model-select/model-select.vue')['default']
    UserUserPassword: typeof import('./../components/user/user-password.vue')['default']
    UserUserPhone: typeof import('./../components/user/user-phone.vue')['default']
    UserUserProfile: typeof import('./../components/user/user-profile.vue')['default']
    WidgetUserBannerUserBanner: typeof import('./../components/widget/user-banner/user-banner.vue')['default']
    WidgetUserServiceUserService: typeof import('./../components/widget/user-service/user-service.vue')['default']
    WidgetUserVersionUserVersion: typeof import('./../components/widget/user-version/user-version.vue')['default']
  }
}
