/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/chat/index" |
  "/pages/about_us/index" |
  "/pages/agreement/index" |
  "/pages/apps/index" |
  "/pages/login/index" |
  "/pages/register/index" |
  "/pages/user/index" |
  "/pages/user/settings" |
  "/pages/webview/index" |
  "/extensions/simple-blog/pages/list/index" |
  "/extensions/simple-blog/pages/detail/index" |
  "/extensions/simple-blog/pages/cate";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/chat/index" | "/pages/apps/index" | "/pages/user/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
