export default {
  google: {
    title: "Google Login Configuration",
    saveConfig: "Save Configuration",
    alert: {
      title: "Please apply for OAuth 2.0 Client ID in Google Cloud Console first",
      linkText: "Go to Google Cloud Console",
    },
    oauthConfig: {
      title: "Google OAuth Configuration",
      description:
        "Go to Google Cloud Console, click APIs & Services > Credentials, and create an OAuth 2.0 Client ID",
    },
    callbackUrl: {
      label: "Callback URL",
      description:
        "In Google Cloud Console, add the following address to the Authorized redirect URIs of your OAuth 2.0 Client ID",
      copyButton: "Copy callback URL",
    },
    clientId: {
      label: "Client ID",
      placeholder: "Paste Google Client ID",
      required: "Please fill in Client ID",
    },
    clientSecret: {
      label: "Client Secret",
      placeholder: "Paste Google Client Secret",
      required: "Please fill in Client Secret",
    },
    saveSuccess: "Settings saved successfully",
    saveFailed: "Failed to save: {message}",
    copied: "Copied to clipboard",
  },
  wechatOA: {
    title: "WeChat Official Account Configuration",
    saveConfig: "Save Configuration",
    messageEncrypt: {
      plain: "Plaintext Mode",
      compatible: "Compatible Mode",
      safe: "Safe Mode",
    },
    toast: {
      saveSuccess: "Saved successfully",
      saveFailed: "Failed to save: {message}",
      copied: "Copied",
      copyFailed: "Failed to copy",
    },
    alert: {
      title:
        "Please apply for a verified WeChat Official Account (Service Account) in WeChat Official Account Platform first",
      linkText: "Go to WeChat Official Account Platform",
    },
    developerInfo: {
      title: "Developer Information",
      description:
        "Go to WeChat Public Platform, click Development > Basic Configuration > Official Account Development Information to set AppID and AppSecret",
      appId: "AppID",
      appIdPlaceholder: "Paste WeChat Official Account AppID",
      appSecret: "AppSecret",
      appSecretPlaceholder: "Paste WeChat Official Account AppSecret",
    },
    serverConfig: {
      title: "Server Configuration",
      url: "URL",
      urlDescription:
        "Go to WeChat Public Platform, click Development > Basic Configuration > Server Configuration, fill in the server address (URL) above",
      urlPlaceholder: "Generated by system based on APP_DOMAIN",
      token: "Token",
      tokenDescription:
        "Go to WeChat Public Platform, click Development > Basic Configuration > Server Configuration, set the Token",
      tokenPlaceholder: "Server configuration Token",
      encodingAESKey: "EncodingAESKey",
      encodingAESKeyDescription:
        "Message encryption key consists of 43 characters, range: A-Z, a-z, 0-9",
      encodingAESKeyPlaceholder: "43 characters, range A-Z, a-z, 0-9",
      messageEncryptType: "Message Encryption Mode",
      copyUrl: "Copy URL",
    },
    featureSettings: {
      title: "Feature Settings",
      businessDomain: "Business Domain",
      businessDomainDescription:
        "Go to WeChat Public Platform, click Settings > Official Account Settings > Feature Settings, fill in the Business Domain",
      businessDomainPlaceholder: "Generated by system based on APP_DOMAIN",
      copyBusinessDomain: "Copy Business Domain",
      jsApiDomain: "JS Interface Security Domain",
      jsApiDomainDescription:
        "Go to WeChat Public Platform, click Settings > Official Account Settings > Feature Settings, fill in the JS Interface Security Domain",
      jsApiDomainPlaceholder: "Generated by system based on APP_DOMAIN",
      copyJsApiDomain: "Copy JS Interface Security Domain",
      webAuthDomain: "Web Authorization Domain",
      webAuthDomainDescription:
        "Go to WeChat Public Platform, click Settings > Official Account Settings > Feature Settings, fill in the Web Authorization Domain",
      webAuthDomainPlaceholder: "Generated by system based on APP_DOMAIN",
      copyWebAuthDomain: "Copy Web Authorization Domain",
    },
    validation: {
      appIdRequired: "Please fill in AppID",
      appSecretRequired: "Please fill in AppSecret",
    },
  },
};
