export default {
  page: {
    title: "Conversation",
    description: "Start a new conversation",
    newConversation: "New Conversation",
  },
  aiGeneratedDisclaimer: "Content generated by AI, please verify carefully",
  // Chat config page
  config: {
    tabs: {
      welcome: "Welcome",
      suggestions: "Suggestions",
      chat: "Chat",
      model: "Model",
    },
    welcomeTab: {
      title: "Welcome Message",
      description: "Title, description and footer displayed on the chat home screen",
      placeholder: {
        welcomeTitle: "e.g., 👋 Hi, How can I help you?",
        footerInfo: "e.g., Content generated by AI, may not be accurate, for reference only.",
      },
      form: {
        welcomeTitle: "Welcome Title",
        welcomeDescription: "Welcome Description",
        footerInfo: "Footer Information",
        footerPlaceholder: "e.g., Content generated by AI, may not be accurate...",
        footerDescription: "Optional tip text at the bottom of the chat area",
      },
    },
    suggestionsTab: {
      title: "Suggestion Options",
      description: "Whether to show suggestion options on the chat page for quick selection",
      form: {
        enableSuggestions: "Enable Suggestion Options",
        enableDescription: "Show suggestion options for quick user selection",
        addNew: "Add New Suggestion",
        inputPlaceholder: "Enter text and click add",
        addedItems: "Added Suggestions",
        empty: 'No suggestions yet, enter above and click "Add"',
        notFilled: "Not filled",
        remove: "Remove",
      },
    },
    chatTab: {
      title: "Chat Settings",
      description: "Attachment upload and chat behavior related settings",
      form: {
        attachmentSizeLimit: "Attachment Size Limit (MB)",
        attachmentSizePlaceholder: "10",
        attachmentSizeDescription:
          "Maximum file size for single attachment upload in megabytes (MB)",
      },
    },
    modelTab: {
      title: "Model Routing",
      description:
        "Specify models for memory extraction, title generation, etc. If not configured, corresponding features will not be enabled",
      tooltip: {
        memoryModel: "Used to extract and write long-term memory from conversations. If not configured, long-term memory will not be read or written.",
        memoryModelHint: "Used to extract long-term memory, can choose lower cost model",
        titleModel: "Used to automatically generate conversation titles and follow-up suggestions. If not configured, automatic generation will not occur.",
        titleModelHint: "Used to auto-generate conversation titles and follow-up suggestions, can choose lower cost model",
        help: "Help",
      },
      placeholder: {
        notEnabled: "Not enabled",
      },
      form: {
        memoryModel: "Memory Extraction Model",
        memoryModelPlaceholder: "Not enabled",
        memoryModelDescription:
          "Used to extract and write long-term memory from conversations. If not configured, long-term memory will not be read or written.",
        memoryModelHint: "Used to extract long-term memory, can choose lower cost model",
        titleModel: "Title Generation Model",
        titleModelPlaceholder: "Not enabled",
        titleModelDescription:
          "Used to automatically generate conversation titles and follow-up suggestions. If not configured, automatic generation will not occur.",
        titleModelHint:
          "Used to auto-generate conversation titles and follow-up suggestions, can choose lower cost model",
      },
    },
    actions: {
      saveSettings: "Save Settings",
      resetSettings: "Reset Settings",
      resetSuccess: "Reset to currently saved configuration",
    },
    validation: {
      welcomeTitleRequired: "Welcome title is required",
      attachmentSizePositive: "Chat attachment size limit must be a positive number (unit: MB)",
    },
  },

  // Chat record page
  record: {
    searchPlaceholder: "Search conversation title, summary or username",
    feedbackFilter: {
      all: "All Feedback",
      highLike: "High Like Rate",
      highDislike: "High Dislike Rate",
      hasFeedback: "Has Feedback",
    },
    conversation: {
      unnamed: "Unnamed Conversation",
      unknownUser: "Unknown User",
      messages: "{count} messages",
      tokens: "{count} tokens",
    },
    empty: {
      noResults: 'No conversations found matching "{keyword}"',
      noData: "No conversation records",
    },
    confirm: {
      deleteTitle: "Delete Confirmation",
      deleteDescription: "Are you sure you want to delete this conversation record?",
    },
    toast: {
      deleteSuccess: "Conversation record deleted",
      deleteFailed: "Failed to delete: {error}",
    },
    feedback: {
      like: "Like",
      dislike: "Dislike",
      reason: "Reason:",
      noAnalysis: "No feedback analysis yet",
      highLikeRate: "High like rate",
      highDislikeRate: "High dislike rate",
      balancedFeedback: "Feedback balanced",
      likeRateHigh: "Higher like rate",
      dislikeRateHigh: "Higher dislike rate",
      thumbsUp: "Thumbs up",
      thumbsDown: "Thumbs down",
      confidence: "Confidence",
      noFeedbackAnalysis: "No feedback analysis yet",
      loadingMessages: "Loading messages...",
    },
    drawer: {
      title: "Conversation Details",
      userLabel: "User:",
      noMessages: "No messages yet",
      confidence: "Confidence",
    },
    user: "User",
    delete: "Delete",
    messages: "messages",
    tokens: "tokens",
  },

  // Shared chat strings
  askAssistantTip: "You can ask questions to learn about relevant content in the knowledge base",
  chat: {
    newChat: "New Chat",
    collapse: "Collapse",
    history: "History",
    noConversations: "No conversations yet",
    noTitle: "No title",
    creator: "Creator:",
  },
};
