import { presetUni } from "@uni-helper/unocss-preset-uni";
import { defineConfig, presetIcons, transformerDirectives, transformerVariantGroup } from "unocss";

export default defineConfig({
    presets: [
        presetUni(),
        presetIcons({
            scale: 1.2,
            warn: true,
            extraProperties: {
                display: "inline-block",
                "vertical-align": "middle",
            },
            // HBuilderX 必须针对要使用的 Collections 做异步导入
            // collections: {
            //   carbon: () => import('@iconify-json/carbon/icons.json').then(i => i.default),
            // },
        }),
    ],
    // transformerDirectives 启用指令功能：主要用于支持 @apply、@screen 和 theme() 等 CSS 指令
    // transformerVariantGroup 启用变体功能
    transformers: [transformerDirectives(), transformerVariantGroup()],
    theme: {
        colors: {
            background: "var(--background)",
            foreground: "var(--foreground)",
            scrollbar: "var(--scrollbar-color)",
            "scrollbar-hover": "var(--scrollbar-color-hover)",
            sidebar: "var(--sidebar)",
            "sidebar-foreground": "var(--sidebar-foreground)",
            primary: "var(--primary)",
            "primary-50": "var(--primary-50)",
            "primary-100": "var(--primary-100)",
            "primary-200": "var(--primary-200)",
            "primary-300": "var(--primary-300)",
            "primary-400": "var(--primary-400)",
            "primary-500": "var(--primary-500)",
            "primary-600": "var(--primary-600)",
            "primary-700": "var(--primary-700)",
            "primary-800": "var(--primary-800)",
            "primary-900": "var(--primary-900)",
            "primary-950": "var(--primary-950)",
            success: "var(--success)",
            "success-50": "var(--success-50)",
            "success-100": "var(--success-100)",
            "success-200": "var(--success-200)",
            "success-300": "var(--success-300)",
            "success-400": "var(--success-400)",
            "success-500": "var(--success-500)",
            "success-600": "var(--success-600)",
            "success-700": "var(--success-700)",
            "success-800": "var(--success-800)",
            "success-900": "var(--success-900)",
            "success-950": "var(--success-950)",
            info: "var(--info)",
            "info-50": "var(--info-50)",
            "info-100": "var(--info-100)",
            "info-200": "var(--info-200)",
            "info-300": "var(--info-300)",
            "info-400": "var(--info-400)",
            "info-500": "var(--info-500)",
            "info-600": "var(--info-600)",
            "info-700": "var(--info-700)",
            "info-800": "var(--info-800)",
            "info-900": "var(--info-900)",
            "info-950": "var(--info-950)",
            warning: "var(--warning)",
            "warning-50": "var(--warning-50)",
            "warning-100": "var(--warning-100)",
            "warning-200": "var(--warning-200)",
            "warning-300": "var(--warning-300)",
            "warning-400": "var(--warning-400)",
            "warning-500": "var(--warning-500)",
            "warning-600": "var(--warning-600)",
            "warning-700": "var(--warning-700)",
            "warning-800": "var(--warning-800)",
            "warning-900": "var(--warning-900)",
            "warning-950": "var(--warning-950)",
            error: "var(--error)",
            "error-50": "var(--error-50)",
            "error-100": "var(--error-100)",
            "error-200": "var(--error-200)",
            "error-300": "var(--error-300)",
            "error-400": "var(--error-400)",
            "error-500": "var(--error-500)",
            "error-600": "var(--error-600)",
            "error-700": "var(--error-700)",
            "error-800": "var(--error-800)",
            "error-900": "var(--error-900)",
            "error-950": "var(--error-950)",
            neutral: "var(--neutral)",
            "neutral-50": "var(--neutral-50)",
            "neutral-100": "var(--neutral-100)",
            "neutral-200": "var(--neutral-200)",
            "neutral-300": "var(--neutral-300)",
            "neutral-400": "var(--neutral-400)",
            "neutral-500": "var(--neutral-500)",
            "neutral-600": "var(--neutral-600)",
            "neutral-700": "var(--neutral-700)",
            "neutral-800": "var(--neutral-800)",
            "neutral-900": "var(--neutral-900)",
            "neutral-950": "var(--neutral-950)",
            secondary: "var(--secondary)",
            "secondary-foreground": "var(--secondary-foreground)",
            muted: "var(--muted)",
            "muted-foreground": "var(--muted-foreground)",
            accent: "var(--accent)",
            "accent-foreground": "var(--accent-foreground)",
            border: "var(--border)",
            "border-muted": "var(--border-muted)",
            "border-accent": "var(--border-accent)",
            "border-inverted": "var(--border-inverted)",
            ring: "var(--ring)",
            "ring-offset": "var(--ring-offset)",
        },
    },
});
